### ISSUE TITLE
Launching start.launch; dependency issues

### ISSUE THREAD

**Issue by rcpilotp51** [LoyVanBeek/wit_ros#11]
@LoyVanBeek 
I'm getting the following error:
```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.3.0) 
doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/kbrown/robot_ws/src/wit_ros/src/wit_ros/wit_node.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "build/bdist.linux-x86_64/egg/OpenSSL/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/SSL.py", line 194, in <module>
AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'
================================================================================REQUIRED process [wit_node-2] has died!
process has died [pid 21752, exit code 1, cmd /home/kbrown/robot_ws/src/wit_ros/src/wit_ros/wit_node.py __name:=wit_node __log:
=/home/kbrown/.ros/log/13932eb2-8882-11e9-96b4-000c2970b3a5/wit_node-2.log].
log file: /home/kbrown/.ros/log/13932eb2-8882-11e9-96b4-000c2970b3a5/wit_node-2*.log
Initiating shutdown!
================================================================================
```

Any suggestions?

**Comment by LoyVanBeek** [comment]
Not really straight away. 
I used `requests` so that I don't have to worry about SSL and all that stuff. Maybe your version of `requests` is out of date or your SSL library? 

When I import requests in a 2.7 (ye olde Ubuntu 16.04) interpreter, I get this:
```python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
``` 
It complains but works AFAIK. At least it doesn't throw an exception when importing.

**Comment by rcpilotp51** [comment]
when i . run the package. it just dies.

not sure... i get the same :(
was fun while it lasted i guess haha

**Comment by LoyVanBeek** [comment]
Have you tried to `sudo pip install requests --upgrade`?

**Comment by rcpilotp51** [comment]
yeah - not sure what else to do at this point

**Comment by LoyVanBeek** [comment]
Let me get this straight: all of a sudden, any place you import `requests` now fails on your system?
Can you try this on a different machine? 

I don't think it's an issue with my code just yet, because my code isn't even executed: the node crashes on `import requests` on line 8 without running anything else.
